FROM tomcat:8.5-alpine
COPY target/first-springboot.war /usr/local/tomcat/webapps/first-springboot.war
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "/usr/local/tomcat/webapps/first-springboot.war"]
